[build]
  publish = "client/build"
  command = "cd client && npm install && CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
